/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PodcastPodcastIdImport } from './routes/podcast/$podcastId'
import { Route as PodcastPodcastIdEpisodeEpisodeIdImport } from './routes/podcast/$podcastId.episode.$episodeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PodcastPodcastIdRoute = PodcastPodcastIdImport.update({
  path: '/podcast/$podcastId',
  getParentRoute: () => rootRoute,
} as any)

const PodcastPodcastIdEpisodeEpisodeIdRoute =
  PodcastPodcastIdEpisodeEpisodeIdImport.update({
    path: '/podcast/$podcastId/episode/$episodeId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/podcast/$podcastId': {
      preLoaderRoute: typeof PodcastPodcastIdImport
      parentRoute: typeof rootRoute
    }
    '/podcast/$podcastId/episode/$episodeId': {
      preLoaderRoute: typeof PodcastPodcastIdEpisodeEpisodeIdImport
      parentRoute: typeof PodcastPodcastIdImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  PodcastPodcastIdRoute.addChildren([PodcastPodcastIdEpisodeEpisodeIdRoute]),
])

/* prettier-ignore-end */
